config/routes.rb
RailsBeginner::Application.routes.draw do
  root to: 'pages#home'

  match '/register',  to: 'users#new',         via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signin',  to: 'sessions#create',         via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help', to: 'pages#help', via: 'get'
  match '/about', to: 'pages#about', via: 'get'

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end
  resources :categories, only: [:show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
  validates :name, presence: true
  validates :github_link, uniqueness: true

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.paginate(page: params[:page], per_page:4)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if signed_in?
      @posts = @current_user.posts.paginate(page: params[:page], per_page:3)
      @comments = @current_user.comments.paginate(page: params[:page], per_page:4)
    end
  end

  def help
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 3)
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "This post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_creator
    access_denied unless signed_in? && (current_user == @post.creator)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, you've Signed in."
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @posts = @user.posts.paginate(page: params[:page], per_page:2)
    @comments = @user.comments.paginate(page: params[:page], per_page:2)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Rails beginner!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your profile was updated"
      redirect_to @user
    else
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :github_link)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You're not allow to do that."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Rails beginner"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def display_datetime(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    !current_user.nil?
  end

  def require_user
    if !signed_in?
      flash[:error] = "You must log in to do that."
      redirect_to root_path
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    user == current_user
  end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.username.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>
<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<%= will_paginate @posts %>

<% @posts.each do |post| %>
    <%= render 'posts/post', post: post %>
<% end %>

<%= will_paginate @posts %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<% if comment.body != "" %>
    <div class="well">
      <em>"<%= comment.body %>"</em>
      <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
      <br/>
      <span class="quiet">by</span> <%= link_to comment.creator.name, user_path(comment.creator) %>
      <small>at <%= display_datetime(comment.created_at) %></small>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://gist.github.com/xdite/8135629">Rails beginner</a>
    by Leo
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Rails beginner", root_path, id: "logo" %>
      <ul class="nav nav-pills">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Categories <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |categories| %>
              <li>
                <%= link_to categories.name, categories %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <nav>
        <% if signed_in? %>
            <%= link_to "New post", new_post_path, class: "btn btn-small btn-success" %>
        <% end %>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Post", posts_path %></li>
          <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.name %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About Me') %>
<h1>About Me</h1>
<p>
  This is the About page for the Rails beginner project (Rails 新手村的作業).
</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is the Help page for the Rails beginner project (Rails 新手村的作業).
</p>

app/views/pages/home.html.erb
<% if !signed_in? %>
    <div class="center hero-unit">
      <h1>Rails beginner</h1>
      <h2>
        This is the Home page for the
        <a href='https://gist.github.com/xdite/8135629'>Rails beginner</a> project (Rails 新手村的作業).
      </h2>

      <%= link_to "Sign up now!", register_path, class: "btn btn-large btn-primary" %>
    </div>

    <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% else %>
    <h5><%= render 'shared/content_title', title: "Your Activity" %></h5>

    <ul class='nav nav-tabs'>
      <li class='<%= 'active' if params[:tab].nil? %>'>
        <%= link_to "Posts (#{@current_user.posts.size})", root_path %>
      </li>
      <li class='<%= 'active' if params[:tab] == 'comments' %>'>
        <%= link_to "Comments (#{@current_user.comments.size})", root_path(tab: 'comments') %>
      </li>
    </ul>

    <% if params[:tab].nil? %>
        <% if @posts.present? %>
            <% @posts.each do |post| %>
                <%= render 'posts/post', post: post %>
            <% end %>
            <%= will_paginate @posts%>
        <% else %>
            <%= 'None' %>
        <% end %>
    <% elsif params[:tab] == 'comments' %>
        <% @comments.each do |comment| %>
            <%= render 'comments/comment', comment: comment, show_post: true %>
        <% end %>
        <%= will_paginate @comments%>
    <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@post) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :url %>
        <%= f.text_field :url %>

        <%= f.label :description %>
        <%= f.text_area :description %>

        <div class='control-group'>
          <%= f.label "Categories" %>
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>

        <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-large btn-primary') %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class='row'>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.name, user_path(post.creator) %>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
        <span>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit Post') %>
<%= render 'shared/content_title', title: 'Editting Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<%= will_paginate %>

<% @posts.each do |post| %>
    <%= render 'post', post: post %>
<% end %>

<%= will_paginate %>

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>
<%= render 'shared/content_title', title: 'Create New Post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>
<% if signed_in? && current_user == @post.creator %>
   <p class='pull-right'>
     [<%= link_to 'edit this post', edit_post_path(@post) %>]
   </p>
<% end %>
<p>
  <%= @post.description %>
</p>

<h5>Comments</h5>

<% @post.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
<% end %>

<% if signed_in? %>
    <div class="row">
      <div class="span6">
        <%= form_for [@post, @comment] do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :body, 'Leave a comment' %>
            <%= f.text_area :body, rows: 3 %>

            <%= f.submit "Create comment", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
<hr/>
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
     <div class="alert alert-error">
         The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
     </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :username %>
        <%= f.text_field :username %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :github %>
        <%= f.text_field :github_link %>

        <%= f.submit @user.new_record? ? 'Register' : 'Update Profile', class: "btn btn-large btn-info" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Profile' %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <% if @user.github_link.present?%>
            <%= link_to @user.github_link,  @user.github_link %>
        <% end%>
      </h1>
    </section>
  </aside>
</div>

<h5><%= @user.name %>'s Activity</h5>

<ul class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
    <%= render(partial: 'posts/post', collection: @posts) || "None" %>
    <%= will_paginate @posts %>
<% elsif params[:tab] == 'comments' %>
    <%= render(partial: 'comments/comment', collection: @comments, locals: {show_post: true}) || "None" %>
    <%= will_paginate @comments%>
<% end %>